---
title: "IA - projeto"
author: "Arthur Vinícius Tomé Rodrigues, João Victor Barroso Mafra, Jobson Lucas Dias da Silva"
date: "23 de fevereiro de 2018"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
require(ggplot2, quietly = TRUE)
require(dplyr, quietly = TRUE)
require(bnlearn, quietly = TRUE)
require(tidyr)
require(reshape2, quietly = TRUE)
library(knitr, quietly = TRUE)
library(reshape2, quietly = TRUE)

```


## Procedimento para ler os dados
```{r, echo=FALSE}
ler_dados = function(arquivo){
  
  require("dplyr", warn.conflicts = FALSE)
  
  file = read.csv(arquivo, stringsAsFactors = TRUE, encoding='UTF-8')
  return (file)
}
```


## Salvar dados dos alunos de cc que tenham nota(exceto os que trancaram).
```{r, echo=FALSE}
##Isso aqui só executa se tiver os dados brutos
alunos_ufcg = ler_dados("alunosUFCGAnon.CSV")

alunos_cc = alunos_ufcg %>% 
  filter(Cod_Curso == 14102100 & Situacao != "Trancado") %>% 
  select(Matricula, Cod_Disciplina, Cod_Evasao, Nome_Disciplina, Media_Disciplina, Periodo, Situacao)

write.csv(alunos_cc, file = "dados_alunos_cc.csv", row.names=FALSE, fileEncoding = "UTF-8")
```


## Selecionar dados dos alunos de CC dos três primeiros períodos
```{r, echo=FALSE}

#disciplinas até o terceiro período ministradas por professores do DSC
disciplinas_escolhidas = c(1411167, 1411180, 1411174, 1411168, 1411181, 1411170, 1411172, 1411179, 1411171, 1109113)

df_alunos_cc = ler_dados("dados_alunos_cc.CSV") %>% 
  filter(Cod_Disciplina %in% disciplinas_escolhidas)
```


## Salvar dados dos alunos de CC com as notas no formato necessário para o modelo Caxalau
```{r, echo=FALSE}
df_cc_notas_simplificadas = df_alunos_cc

#transformar notas em int
df_cc_notas_simplificadas$Media_Int = lapply(df_cc_notas_simplificadas$Media_Disciplina, 
                                                 function(x) round(x*10, digits = 0))

#transformar reprovados por falta em reprovado, já que isso não vai interferir na nossa análise
df_cc_notas_simplificadas[df_cc_notas_simplificadas == "Reprovado por Falta"] = as.character("Reprovado")
#pode ser feito com lapply: df_cc...$Situacao = lapply(df_cc...$Situacao, function(x) ifelse(x == "Aprovado", "Aprovado", "Reprovado")) 

#transformar para df -> tentar ordenar colunas criadas resulta em erro, pois contém lists e não vectors
df_cc_notas_simplificadas = as.data.frame(lapply(df_cc_notas_simplificadas, unlist))

#retirar espaços dos nomes das disciplinas
df_cc_notas_simplificadas = df_cc_notas_simplificadas %>% 
  mutate(Nome_Disciplina = as.factor(gsub(" ", ".", Nome_Disciplina)))

```


## Transformar em coluna as disciplinas (facilita manipular média e usá-la como evidência na rede bayesiana)
```{r}

xx = df_cc_notas_simplificadas

#transformar cada disciplina (código dela) em uma coluna
xx = xx %>% dcast(Matricula + 
                    Periodo + 
                    Media_Int + 
                    Cod_Disciplina + 
                    Cod_Evasao + 
                    Nome_Disciplina + 
                    Situacao ~ Cod_Disciplina, value.var = "Media_Int") %>%
  group_by(Matricula) 

disciplins = as.character(disciplinas_escolhidas)

# preencher a coluna com a média inteira da disciplina
# 200 significa que o cara tirou 0 (uma forma de diferenciar do 0 que substitui NA)
xx[disciplins] = lapply(xx[disciplins], 
                        function(x){ 
                            ifelse(is.na(x), 0, ifelse(x == 0, 200, x))
                            
                        })

names(xx) = c("Matricula", "Periodo", "Media_Int", "Cod_Disciplina", "Cod_Evasao", "Nome_Disciplina", "Situacao", "Discreta", "P1", "P2", "Grafos", "TC", "Eda", "IC", "Leda", "LP1", "LP2")

xx = as.data.frame(lapply(xx, unlist))

disciplinas_primeiro_periogo = c("1411174", "1411180", "1411167", "P1", "LP1", "IC")
disciplinas_segundo_periogo = c("1109113", "1411168", "1411181", "1411170", "P2", "LP2", "Discreta", "Grafos")
disciplinas_terceiro_periogo = c("1411179", "1411171", "1411172", "Eda", "Leda", "TC")


##adicionar o período de acordo com as disciplinas que cursou 
xx$Periodo_Curso = ifelse(
  xx$Cod_Disciplina %in% disciplinas_terceiro_periogo, 3, 
  ifelse(
    xx$Cod_Disciplina %in% disciplinas_segundo_periogo, 2, 1
    )
  )

#colocando os dados no formato de todos em uma única linha - facilitar execução do caxalau
dados_caxalau = xx %>% group_by(Matricula, Periodo, Periodo_Curso) %>% 
  summarise_at(c("P1", "P2", "LP1", "IC", "LP2", 
                 "Discreta", "Eda", "Leda", "Grafos", "TC"), sum)

write.csv(xx, file = "alunos_notas_simplif.csv", row.names=FALSE, fileEncoding = "UTF-8")
write.csv(dados_caxalau, file = "abaco.csv", row.names=FALSE, fileEncoding = "UTF-8")

```
