---
title: "IA - projeto"
author: "Arthur Vinicius Tomé Rodrigues, João Victor Barroso Mafra, Jobson Lucas Dias da Silva"
date: "23 de fevereiro de 2018"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
require(ggplot2, quietly = TRUE)
require(dplyr, quietly = TRUE)
require(bnlearn, quietly = TRUE)
require(tidyr)
require(reshape2, quietly = TRUE)
library(knitr, quietly = TRUE)
library(reshape2, quietly = TRUE)

```


## Ler arquivo com dados alunos de cc
```{r, echo=FALSE}
df_alunos_cc = ler_dados("alunos_notas_simplif.csv") %>% select(-GI)
```

```{r}
disciplinas_primeiro_periogo = c("1411174", "1411180", "1411167", "P1", "LP1", "IC")
disciplinas_segundo_periogo = c("1109113", "1411168", "1411181", "1411170", "P2", "LP2", "Discreta", "Grafos")
disciplinas_terceiro_periogo = c("1411179", "1411176", "1411171", "1411172", "Eda", "Leda", "TC")

##adicionar o período de acordo com as disciplinas que cursou 
df_alunos_cc$Periodo_Curso = ifelse(
  df_alunos_cc$Cod_Disciplina %in% disciplinas_terceiro_periogo, 3, 
  ifelse(
    df_alunos_cc$Cod_Disciplina %in% disciplinas_segundo_periogo, 2, 1
    )
  )

#colocando os dados no formato de todos em uma única linha - facilitar execução do caxalau
abaco = df_alunos_cc %>% group_by(Matricula, Periodo, Periodo_Curso) %>% 
  summarise_at(c("P1", "P2", "LP1", "IC", "LP2", 
                 "Discreta", "Eda", "Leda", "Grafos", "TC"), sum)

```




## Range para as notas do modelo caxalau
```{r}
#Gerar o range de até 1 ponto (nesse caso 10 porque foi transformado em inteiro para funcionar na rede bayesiana) para usar no modelo caxalau na hora de filtrar os dados. 
# Por exemplo, se a nota for x = 55, x = 51 ou mesmo x = 50 , então o range será [50,60]. 
# O 100 é o caso especial, logo faremos [90, 100] 
range_notas = function(x) {
  ifelse(x != 100,
        (x - (x %% 10)):(x - (x %% 10) + 10),
        (90:100))
}
```


## Transformar em fatores -> usar rede bayesiana
```{r}
cc_notas_simplificadas = df_alunos_cc

##dados para o modelo gerado pelo R 
col_names = colnames(df_alunos_cc)
df_alunos_cc[, col_names] = lapply(df_alunos_cc[, col_names], factor)

##dados para o modelo usado pelo Caxalau
col_names_simp = colnames(cc_notas_simplificadas)
cc_notas_simplificadas[, col_names_simp] = lapply(cc_notas_simplificadas[, col_names_simp], factor)

```


## Elaborando as relações relevantes
```{r}
#Hill climbing
res <- hc(df_alunos_cc)

relations = res$arcs
to_rel = relations[, 2]
from_rel = relations[, 1]
relations[, 1] = to_rel
relations[, 2] = from_rel

#trocando as relacoes
tmp = relations[2, 2]
relations[2, 2] = relations[2, 1]
relations[2, 1] = tmp

tmp = relations[3, 2]
relations[3, 2] = relations[3, 1]
relations[3, 1] = tmp

relations = rbind(relations, 
                  c("Leda", "Situacao"), 
                  c("TC", "Situacao"), 
                  c("Eda", "Situacao"), 
                  c("Grafos", "Situacao"), 
                  c("GI", "Situacao"),
                  c("P1", "P2"), 
                  c("LP1", "P2"),  
                  c("IC", "P2"),  
                  c("P1", "LP2"), 
                  c("LP1", "LP2"),  
                  c("IC", "LP2"), 
                  c("P1", "Grafos"), 
                  c("LP1", "Grafos"),
                  c("IC", "Leda"), 
                  c("P1", "Leda"), 
                  c("LP1", "Leda"),
                  c("Grafos", "Eda"),
                  c("P2", "Eda"), 
                  c("LP2", "Eda"),
                  c("Discreta", "TC"),
                  c("IC", "TC"), 
                  c("Grafos", "TC")
                  )

res$arcs = relations

plot(res)
```


## Gerar BN para modelo simples para os períodos
```{r}
fittedbn <- bn.fit(res, data = df_alunos_cc, method="mle")

#todo mundo que colocou, se deu baixo, todo mundo vai ser aprovado. Se deu moderado, coloco alguns randomicos para ser reprovado
prob_reprovar_1st_per_simples = cpquery(fittedbn, 
                                          event = (Situacao == "Reprovado"), 
                                          evidence = (Cod_Disciplina %in% disciplinas_primeiro_periogo))

prob_reprovar_2nd_per_simples = cpquery(fittedbn, 
                                          event = (Situacao == "Reprovado"), 
                                          evidence = (Cod_Disciplina %in% disciplinas_segundo_periogo))


prob_reprovar_3rd_per_simples = cpquery(fittedbn, 
                                          event = (Situacao == "Reprovado"), 
                                          evidence = (Cod_Disciplina %in% disciplinas_terceiro_periogo))

```


## Gerar BN para modelo safatraio para os períodos
```{r, echo=False, quietly = TRUE}
disciplinas_primeiro_periogo = c("1411174", "1411180", "1411167")
disciplinas_segundo_periogo = c("1109113", "1411168", "1411181", "1411170")
disciplinas_terceiro_periogo = c("1411179", "1411176", "1411171", "1411172")

disciplinas_interesse = c("1411168", "1411174", "1411180", "1411167")

candidatos_p1_medias = df_alunos_cc %>% 
  filter(Cod_Disciplina %in% disciplinas_primeiro_periogo) %>% 
  filter(P1 == 55) %>% select(Matricula)

tmp_alunos = as.array(candidatos_p1_medias$Matricula)

alunos_filtrados = df_alunos_cc %>% filter(Matricula %in% tmp_alunos & 
                                           Cod_Disciplina %in% disciplinas_interesse
                                           )

fittedbn_safa = bn.fit(res, 
                        data = alunos_filtrados, 
                        method="mle")


#todo mundo que colocou, se deu baixo, todo mundo vai ser aprovado. Se deu moderado, coloco alguns randomicos para ser reprovado
#não faz sentido gerar para o primeiro período pq não há pré-requisitos

safa_prob_reprovar_2nd_per = cpquery(fittedbn_safa, 
                                     event = (Situacao == "Reprovado" & 
                                              Cod_Disciplina == "1411168"), 
                                     evidence = (P1 == 55))

safa_prob_aprovar_2nd_per = cpquery(fittedbn_safa, 
                                     event = (Situacao == "Aprovado" & 
                                              Cod_Disciplina == "1411168"), 
                                     evidence = (P1 == 100 & IC == 100))

```





## Gerar BN para modelo simples para os períodos - teste
```{r}
disciplinas_primeiro_periogo = c("1411174", "1411180", "1411167")
disciplinas_segundo_periogo = c("1109113", "1411168", "1411181", "1411170")
disciplinas_terceiro_periogo = c("1411179", "1411176", "1411171", "1411172")

fittedbn <- bn.fit(res, data = df_alunos_cc, method="mle")

prob_reprovar_2nd_per_simples = cpquery(fittedbn, 
                                          event = (Situacao == "Reprovado"), 
                                          evidence = (Cod_Disciplina == "1411167" & 
                                                        Media_Int == 0))


prob_reprovar_3rd_per_simples = cpquery(fittedbn, 
                                          event = (Situacao == "Reprovado"), 
                                          evidence = (Cod_Disciplina %in% disciplinas_terceiro_periogo))

```

